version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux
    container_name: sqlserver
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123456
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql
