name: Build and deploy Backend on Azure
run-name: "#${{ github.run_number }} - ${{ github.ref_name }} - ${{ github.sha }} - Backend"

on:
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: VCBRDemoHttpApiHost20230714102118
  AZURE_WEBAPP_PACKAGE_PATH: src\VCBRDemo.HttpApi.Host\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.x
  WORKING_DIRECTORY: aspnet-core\src\VCBRDemo.HttpApi.Host
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Install abp
        run: dotnet tool install -g Volo.Abp.Cli
      - name: Install abp libs
        run: abp install-libs "aspnet-core"
      - name: Restore
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
      - name: Build
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
      - name: Test
        run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
      - name: Inject secrets to application
        uses: microsoft/variable-substitution@v1
        with:
          files: "${{ github.workspace }}/aspnet-core/src/VCBRDemo.HttpApi.Host/appsettings.json"
        env:
          ConnectionStrings.Default: ${{ secrets.DATABASE_CONNRECTION_STRING }}
      - name: Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.VCBRDemoHttpApiHost20230714102118_562D }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
