# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Frontend on Azure
run-name: "#${{ github.run_number }} - ${{ github.ref_name }} - ${{ github.sha }} - Frontend"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: angular
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Install yarn
        run: npm install --global yarn
          
      - name: Install  packages
        run: yarn install
      
      - name: Build
        run: yarn run build
      
      - name: Archive artifact
        uses: ihiroky/archive-action@v1
        with:
          root_dir: ./dist/apollo-eapproval/dev-build
          file_path: publish.zip
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dev-package
          path: ./publish.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: dev-package

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'vtpdemo'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1B1A96AEB5374F0BA6AEDBD925E68621 }}
          package: .
